import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import { config } from '../config.js'
import type { KnowledgeItem } from '../types/index.js'

const BASE_DIR = config.memoryDir
const INDEX_PATH = join(BASE_DIR, 'knowledge_index.md')

function ensureDir(dir: string): void {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
}

function formatDate(ts: number): string {
  return new Date(ts).toISOString().slice(0, 10)
}

function shortPath(p: string): string {
  return p.replace(homedir(), '~')
}

function formatLogItem(item: KnowledgeItem, isNew: boolean): string {
  const badge = isNew ? 'new' : `×${item.askCount}`
  const arrow = !isNew ? ' ↑' : ''
  const tags = item.tags.length ? ` · ${item.tags.join(', ')}` : ''
  return [
    `### [${item.category}, ${badge}] **${item.title}**${arrow}`,
    item.content,
    `\`${shortPath(item.projectPath)}\`${tags}`,
  ].join('\n')
}

export class KnowledgeWriter {
  /**
   * Append newly extracted/updated items to today's knowledge_log.md.
   * newIds: set of item ids that were just inserted (vs updated).
   */
  appendToDaily(items: KnowledgeItem[], newIds: Set<number>, projectPath: string): void {
    if (items.length === 0) return

    ensureDir(BASE_DIR)
    const today = formatDate(Date.now())
    const dayDir = join(BASE_DIR, today)
    ensureDir(dayDir)

    const logPath = join(dayDir, 'knowledge_log.md')
    const project = shortPath(projectPath)
    const time = new Date().toTimeString().slice(0, 5)

    const lines: string[] = []
    if (!existsSync(logPath)) {
      lines.push(`# Knowledge Log — ${today}\n`)
    }
    lines.push(`\n## ${time} · ${project}`)
    for (const item of items) {
      const isNew = item.id === undefined || newIds.has(item.id)
      lines.push(formatLogItem(item, isNew))
    }

    writeFileSync(logPath, lines.join('\n') + '\n', { flag: 'a' })
  }

  /**
   * Overwrite knowledge_index.md with the top items sorted by weight.
   * Called after each incremental extraction to keep the index fresh.
   */
  updateIndex(topItems: KnowledgeItem[]): void {
    if (topItems.length === 0) return
    ensureDir(BASE_DIR)

    const now = new Date().toISOString().slice(0, 16).replace('T', ' ')
    const concepts = topItems.filter(i => i.category === 'concept')
    const howtos   = topItems.filter(i => i.category === 'howto')
    const projects = topItems.filter(i => i.category === 'project')

    const formatIdx = (item: KnowledgeItem, rank: number): string => {
      const tags = item.tags.length ? ` · ${item.tags.join(', ')}` : ''
      return [
        `${rank}. [×${item.askCount}] **${item.title}** — weight ${item.weight.toFixed(1)}`,
        `   ${item.content}`,
        `   \`${shortPath(item.projectPath)}\`${tags}`,
      ].join('\n')
    }

    const lines = [
      '# Knowledge Index',
      `> Last updated: ${now}`,
      '> Auto-generated by nous · Full review: `nous:review`',
    ]

    let rank = 1
    if (concepts.length) {
      lines.push('\n## Concepts')
      for (const item of concepts) lines.push(formatIdx(item, rank++))
    }
    if (howtos.length) {
      lines.push('\n## How-to')
      for (const item of howtos) lines.push(formatIdx(item, rank++))
    }
    if (projects.length) {
      lines.push('\n## Project-specific')
      for (const item of projects) lines.push(formatIdx(item, rank++))
    }

    writeFileSync(INDEX_PATH, lines.join('\n') + '\n')
  }
}
